apiVersion: v1
kind: Service
metadata:
  name: my-postgres # name of our services
  labels:
    app: postgres
spec:
  type: LoadBalancer # expose the service as loadbalancer, see kubernetes docs
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres #name of our deployments
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres #deploy that match our selector labels
      tier: postgresql
  replicas: 1 # number of replica set
  template:
    metadata:
      labels:
        app: postgres # our postgres container label
        tier: postgresql
    spec:
      containers:
        - name: my-postgres
          image: postgres:10.7
          ports:
            - containerPort: 5432 # expose container port
          envFrom:
            - configMapRef:
                name: my-postgres-config # get env value from config map
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # mount point of do pv
              name: my-postgres-volume # name of our mount point pv
      volumes:
        - name: my-postgres-volume
          persistentVolumeClaim:
            claimName: csi-pvc # name of pv created in pvc.yaml