apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc # this our name csi-pvc and will accessed within clusters
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # amount of pv we need
  storageClassName: do-block-storage
